### ISSUE TITLE
Solution does not work

### ISSUE THREAD

**Issue by regasoraini** [exogee-technology/graphweaver#183]
**Describe the bug**
i follow the steps in the website : https://graphweaver.com/docs/quick-start
and i face this issue ( image attached )

**Screenshots or Screencasts**

`
× Unhandled exception in handler 'graphweaver-backend'.
× Runtime.ImportModuleError: Error: Cannot find module 'index'
  Require stack:
  - D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js
      at _loadUserApp (D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js:310:15)
      at async module.exports.load (D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js:341:21)
      at async InProcessRunner.run (file:///D:/Projects/Test%20Projects/test1/node_modules/.pnpm/serverless-offline@12.0.2_serverless@3.34.0/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:41:21)
      at async MessagePort.<anonymous> (file:///D:/Projects/Test%20Projects/test1/node_modules/.pnpm/serverless-offline@12.0.2_serverless@3.34.0/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)
× Error: Cannot find module 'index'
  Require stack:
  - D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js

ANY / (λ: graphweaver-backend)
× Unhandled exception in handler 'graphweaver-backend'.
× Runtime.ImportModuleError: Error: Cannot find module 'index'
  Require stack:
  - D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js
      at _loadUserApp (D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js:310:15)
      at async module.exports.load (D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js:341:21)
      at async InProcessRunner.run (file:///D:/Projects/Test%20Projects/test1/node_modules/.pnpm/serverless-offline@12.0.2_serverless@3.34.0/node_modules/serverless-offline/src/lambda/handler-runner/in-process-runner/InProcessRunner.js:41:21)
      at async MessagePort.<anonymous> (file:///D:/Projects/Test%20Projects/test1/node_modules/.pnpm/serverless-offline@12.0.2_serverless@3.34.0/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)
× Error: Cannot find module 'index'
  Require stack:
  - D:\Projects\Test Projects\test1\node_modules\.pnpm\serverless-offline@12.0.2_serverless@3.34.0\node_modules\serverless-offline\src\lambda\handler-runner\in-process-runner\aws-lambda-ric\UserFunction.js
`

**Desktop (please complete the following information):**

- OS and version: [Windows 10]

**Comment by thekevinbrown** [comment]
Thanks for the report! We'll try the latest version out on Win 10 and see if we can reproduce.

**Comment by thekevinbrown** [comment]
Just a note to let you know that we can reproduce and are working on it now. 👍

**Comment by steve-keep** [comment]
Hi @regasoraini We have resolved the issues with running Graphweaver on Windows and have tested the latest release (`0.2.10`) on Windows 10.

It would be great if you could give it another go and thanks again for raising the issue!
