### ISSUE TITLE
Graphweaver Core: Project does not build once a data source is imported using the CLI

### ISSUE THREAD

**Issue by agaw** [exogee-technology/graphweaver#246]
**Describe the bug**
Once a data source has been imported, attempting to run `pnpm build` in the project root results in several fatal errors relating to missing dependencies.

**To Reproduce**

1. Follow the "Quick Start" guide to initialise a new Graphweaver project: [Docs Link](https://graphweaver.com/docs/quick-start)
2. Follow the "Importing A Database" guide to create entity files for any existing database. [Docs Link](https://graphweaver.com/docs/importing-a-database)
3. Attempt to execute a `pnpm build` in the project root.

**Expected behavior**
The build process succeeds.

**Actual behavior**
The following errors are printed to the console:
```
> test-project-2@0.1.0 build /Users/adam/code/experiments/test-project-2
> graphweaver build

Building backend....
 - Building ./src/backend/index => dist/backend/index.js
✘ [ERROR] Could not resolve "pg-query-stream"

    node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/postgres/index.js:192:16:
      192 │       : require('pg-query-stream');
          ╵                 ~~~~~~~~~~~~~~~~~

  You can mark the path "pg-query-stream" as external to exclude it from the bundle, which will
  remove this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "mysql"

    node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/mysql/index.js:23:19:
      23 │     return require('mysql');
         ╵                    ~~~~~~~

  You can mark the path "mysql" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

✘ [ERROR] Could not resolve "better-sqlite3"

    node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/better-sqlite3/index.js:7:19:
      7 │     return require('better-sqlite3');
        ╵                    ~~~~~~~~~~~~~~~~

  You can mark the path "better-sqlite3" as external to exclude it from the bundle, which will
  remove this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "tedious"

    node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/mssql/index.js:94:24:
      94 │     const tds = require('tedious');
         ╵                         ~~~~~~~~~

  You can mark the path "tedious" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

✘ [ERROR] Could not resolve "oracledb"

    node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/oracledb/index.js:37:29:
      37 │     const oracledb = require('oracledb');
         ╵                              ~~~~~~~~~~

  You can mark the path "oracledb" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

✘ [ERROR] Could not resolve "oracledb"

    node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/oracledb/utils.js:40:27:
      40 │   const oracledb = require('oracledb');
         ╵                            ~~~~~~~~~~

  You can mark the path "oracledb" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

gw-bin.js build [environment]

Builds your graphweaver project for deployment.

Positionals:
  environment  Choose whether you want to build the backend, frontend, or both.
               [string] [choices: "backend", "frontend", "all"] [default: "all"]

Options:
  --version      Show version number                                   [boolean]
  --help         Show help                                             [boolean]
  --adminUiBase  Specify the base path for the Admin UI  [string] [default: "/"]

Error: Build failed with 8 errors:
node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28: ERROR: Could not resolve "mock-aws-s3"
node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23: ERROR: Could not resolve "nock"
node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/better-sqlite3/index.js:7:19: ERROR: Could not resolve "better-sqlite3"
node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/mssql/index.js:94:24: ERROR: Could not resolve "tedious"
node_modules/.pnpm/knex@2.5.1_pg@8.11.1_sqlite3@5.1.6/node_modules/knex/lib/dialects/mysql/index.js:23:19: ERROR: Could not resolve "mysql"
...
    at failureErrorWithLog (/Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:1046:63)
    at buildResponseToResult (/Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:1264:7)
    at /Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:1377:14
    at /Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/adam/code/experiments/test-project-2/node_modules/.pnpm/esbuild@0.15.5/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "mock-aws-s3"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "nock"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "better-sqlite3"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "tedious"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "mysql"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "oracledb"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "oracledb"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "pg-query-stream"'
    }
  ],
  warnings: []
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Desktop (please complete the following information):**

- OS and version: MacOS Sonoma 14.2.1 (23C71)

**Additional context**
There is an undocumented workaround for this issue which involves creating a `graphweaver-config.js` file in the project root with the following contents, which marks the missing dependencies as external:
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { merge } = require('lodash');

module.exports = {
	build: {
		onResolveEsbuildConfiguration: (config) => {
			const newConfig = merge(
				{
					external: [
						'pg-native',
						'bun:ffi',
						'mysql',
						'sqlite3',
						'better-sqlite3',
						'oracledb',
						'tedious',
						'pg-query-stream',
						'graphql-type-json',
						'nock',
						'mock-aws-s3',
					],
				},
				config
			);

			return newConfig;
		},
	},
};
```

**Comment by agaw** [comment]
I have confirmed this was fixed as part of https://github.com/exogee-technology/graphweaver/pull/253, closing issue.
